version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: clothing_store
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app_network

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=clothing_store
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge